-- ==========================================================
-- Migração 07 — Histórico de comissões importadas por NF
-- Rode este SQL no Supabase (SQL Editor) antes de usar o
-- botão "Importar Resumo (NF)" em Baixar Parcelas.
-- ==========================================================

create table if not exists comissoes_pagas (
    id               bigint generated by default as identity primary key,
    administradora   text,
    periodo_inicio   text,          -- ex: 16/07/2026
    periodo_fim      text,          -- ex: 31/07/2026
    mes_competencia  text,          -- ex: 2026-07 (usado para agrupar o histórico)
    grupo            text,
    cota             text,
    parcela          text,          -- nº da parcela da comissão (Pcl no PDF)
    cliente          text,
    vendedor         text,
    credito          numeric,       -- valor da carta / crédito
    valor_nota       numeric,       -- comissão bruta (valor da nota)
    imposto_pct      numeric,
    valor_imposto    numeric,
    valor_liquido    numeric,
    breno            numeric,
    uriel            numeric,
    data_pagamento   text,
    origem           text default 'NF',
    chave_unica      text,          -- liga com status_comissoes (baixa da parcela)
    data_importacao  timestamptz default now()
);

-- Índices para acelerar o histórico e a checagem de duplicidade
create index if not exists idx_comissoes_pagas_mes   on comissoes_pagas (mes_competencia);
create index if not exists idx_comissoes_pagas_chave on comissoes_pagas (chave_unica);
