-- ==========================================================
-- Migração 09 — Fila de automação (Oferta de Lances / Boletos)
-- Rode este SQL no Supabase (SQL Editor) antes de usar a tela
-- "Ofertar Lance".
--
-- Como funciona:
--   * O CRM (Streamlit, na nuvem) apenas GRAVA pedidos aqui.
--   * O Worker (Playwright, no PC do escritório) LÊ os pedidos
--     PENDENTES, executa no Newcon e ATUALIZA o status/mensagem.
-- ==========================================================

create table if not exists fila_automacao (
    id             bigint generated by default as identity primary key,

    tipo           text    not null default 'LANCE',   -- LANCE | BOLETO (boletos entram depois)

    -- Identificação da cota (espelho da tabela vendas para o Worker não depender de join)
    venda_id       bigint,                              -- vendas.id (liga com a cota de origem)
    cliente        text,
    vendedor       text,
    produto        text,
    administradora text,
    grupo          text,
    cota           text,

    -- Parâmetros do lance
    tipo_lance     text,                                -- 'Lance Fixo' | 'Lance Livre'
    valor_lance    numeric,                             -- usado no Lance Livre (percentual ou valor)

    -- Controle de execução (preenchido pelo Worker)
    status         text    not null default 'PENDENTE', -- PENDENTE | PROCESSANDO | SUCESSO | ERRO
    mensagem       text,                                -- msg de confirmação do Newcon OU o erro
    tentativas     int     not null default 0,

    -- Auditoria
    solicitado_por text,                                -- login do usuário que clicou "Ofertar"
    criado_em      timestamptz not null default now(),
    iniciado_em    timestamptz,                         -- quando o Worker pegou o pedido
    concluido_em   timestamptz                          -- quando terminou (sucesso ou erro)
);

-- O Worker busca sempre os PENDENTES mais antigos primeiro
create index if not exists idx_fila_status  on fila_automacao (status, criado_em);
-- Para mostrar no CRM o último lance por cota
create index if not exists idx_fila_venda   on fila_automacao (venda_id, criado_em desc);
